#!/usr/bin/env bash

xrdb -merge .config/colortheme.Xresources

xset r rate 200 100
xset dpms 0 1800 3600
xset m 1/1 0
xset s off

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

feh --bg-fill local/space-wallpaper.jpg  > /dev/null 2>&1

# calculate fontsize that fits screen
FS=$(fontsize)
echo "URxvt.font: xft:Iosevka:pixelsize=${FS},xft:DejaVu Sans Mono:pixelsize=${FS}" | xrdb -merge
