#!/usr/bin/env bash

xrdb -merge .config/colortheme.Xresources
xrdb -merge .config/xresources_iosevka

xset r rate 200 100
xset +fp $HOME/.local/share/fonts
xset +fp $HOME/.fonts
xset dpms 0 1800 3600
xset m 1/1 0
xset s off

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr
DEV=$(xinput list | grep "TouchPad" | cut -f 2 | cut -d "=" -f 2)
xinput set-prop $DEV "Device Enabled" 0 || 0

xautolock -time 1 -locker slock -notify 30 &
redshift -t 6500:2600 -l 22:114 &

feh --bg-fill local/space-wallpaper.jpg  > /dev/null 2>&1
wmname LG3D

urxvtd -q -f -o
