#!/usr/bin/env bash

if [ "$DISPLAY" ]; then

    if [ "$(hostname)" == "lulus" ]; then
        xrdb -merge .config/xresources_fira
    elif [ "$(hostname)" == "mathis-pc" ]; then
        xrdb -merge .config/xresources_fira
    else
        xrdb -merge .config/base16-gruvbox-light-medium-256.Xresources
        xrdb -merge .config/xresources_iosevka
    fi

    setxkbmap -option ctrl:backspace -variant colemak
    xset r rate 200 100
    xset +fp $HOME/.local/share/fonts
    xset +fp $HOME/.fonts
    xrdb -merge ~/.Xresources
    xsetroot -cursor_name left_ptr
    DEV=$(xinput list | grep "TouchPad" | cut -f 2 | cut -d "=" -f 2)
    xinput set-prop $DEV "Device Enabled" 0 || 0
    bash $HOME/.fehbg 2>&1 || true
    xset dpms 0 1800 3600 &
    xset m 1/1 0 &
    xset s off &
    xautolock -time 1 -locker slock -notify 30 &
    redshift -t 6500:2600 -l 22:114 &
    feh --bg-fill space-wallpaper.jpg  > /dev/null 2>&1

    urxvtd -q -f -o

    # dualhead
    if [ "$(xrandr | grep ' connected' | wc -l)" -eq 2 ]; then
        xrandr --output HDMI2 --left-of VGA1 --output VGA1 || true # desktop
        xrandr --output DVI-D-0 --left-of DVI-I-1 --output DVI-I-1 || true # office nvidia card
    fi

fi


