#!/usr/bin/env bash

if [ "$DISPLAY" ]; then

    xrdb -merge .config/base16-gruvbox-light-medium-256.Xresources
    xrdb -merge .config/xresources_iosevka

    xset r rate 200 100
    xset +fp $HOME/.local/share/fonts
    xset +fp $HOME/.fonts
    xset dpms 0 1800 3600
    xset m 1/1 0
    xset s off

    xrdb -merge ~/.Xresources
    xsetroot -cursor_name left_ptr
    DEV=$(xinput list | grep "TouchPad" | cut -f 2 | cut -d "=" -f 2)
    xinput set-prop $DEV "Device Enabled" 0 || 0

    xautolock -time 1 -locker slock -notify 30 &
    redshift -t 6500:2600 -l 22:114 &

    feh --bg-fill local/space-wallpaper.jpg  > /dev/null 2>&1
    wmname LG3D

    urxvtd -q -f -o

    # dualhead
    if [ "$(xrandr | grep ' connected' | wc -l)" -eq 2 ]; then
        xrandr --output HDMI2 --left-of VGA1 --output VGA1 || true # desktop
        xrandr --output DVI-D-0 --left-of DVI-I-1 --output DVI-I-1 || true # office nvidia card
    fi

fi


