#!/usr/bin/env bash
set -euxo pipefail

error_notify() {
  notify-send 'Update failed!'
}

trap 'error_notify' ERR

sudo nixos-rebuild switch

home-manager switch

~/.emacs.d/bin/doom -y u
~/.emacs.d/bin/doom -y re

notify-send "Update complete!"
