#!/usr/bin/env bash
set -euxo pipefail

pushd nixpkgs
git fetch --all
git checkout system
git rebase channels/nixos-unstable
git push --force origin system
popd

pushd home-nixpkgs/home-manager
git checkout master
git pull origin master
popd

pushd home-nixpkgs/doom-emacs
git checkout develop
git pull origin develop
popd
